### PR TITLE
Contact driver

### PR DESCRIPTION
**Pull request by hanc2006**

### CODE REVIEW

**Comment by feralheart** [comment]
Hi,
Thank you for your contribution.
Is this the upgrade of #52 ?

**Comment by holtkamp** [comment]
@feralheart indeed, it also solves https://github.com/botman/driver-telegram/issues/64

So +1 for merging this PR. Have been using https://github.com/hanc2006/driver-telegram/tree/contact-driver for quite some time without any issues.

**Comment by feralheart** [comment]
Thank you for your clarification @holtkamp 
Fixes #64

**Comment by holtkamp** [comment]
Thanks @feralheart!

Does this justify tagging a new (minor) release?

**Comment by feralheart** [comment]
> @holtkamp: Does this justify tagging a new (minor) release?

I will tag a release soon, but before I want to check the other PRs as well

**Pull request merged**
