### PR TITLE
added contact driver

### PR DESCRIPTION
**Pull request by hanc2006**

### CODE REVIEW

**Comment by holtkamp** [comment]
Nice contribution @hanc2006 ! 

@mpociot are you considering a new minor release for this?

**Comment by holtkamp** [comment]
mmm, when looking closer it seems some files are missing?

- `BotMan\Drivers\Telegram\TelegramContactDriver` 
-  `BotMan\BotMan\Messages\Attachments\Contact`

So I suppose this is work-in-progress 😄

**Comment by hanc2006** [comment]
Hi @holtkamp,
`BotMan\BotMan\Messages\Attachments\Contact` is not in this repository. Is a part of botman/botman project. You can use the contact attachment inside a conversation like:
```
...
$this->askForContact('Please send us your phone number in order to be able to connect your account.', function (Contact $contact) {
     $this->say('Thank you. Your contact has been linked.');
}
...
```

**Comment by holtkamp** [comment]
@hanc2006 thanks for the swift heads-up!

Aah, yeah, found it here: https://github.com/botman/botman/blob/cfa07d5734fdaf2b6cc4c8eb501b747d93c1f2b3/src/Messages/Attachments/Contact.php

But what about `BotMan\Drivers\Telegram\TelegramContactDriver`?

When looking at the master branch of this repo https://github.com/botman/driver-telegram, no such class is currently party of it...

https://github.com/botman/driver-telegram/tree/5ced1597ed9c7eae842ca9c09ef61478821172db/src

hence my doubt...

**Comment by hanc2006** [comment]
Yes right. It’s for manual loading the driver. I will pull the new file with changes 👍

**Comment by holtkamp** [comment]
@hanc2006 I noticed you updated the feature branch: https://github.com/hanc2006/driver-telegram/tree/contact-driver

with the [TelegramContactDriver](https://github.com/hanc2006/driver-telegram/blob/812fb55001c810581e2e12f22bb101d870ec4e8c/src/TelegramContactDriver.php)

Looking forward to work with this!

**Comment by holtkamp** [comment]
@hanc2006 bump on this? 

the [TelegramContactDriver](https://github.com/hanc2006/driver-telegram/blob/812fb55001c810581e2e12f22bb101d870ec4e8c/src/TelegramContactDriver.php)

is still missing from https://github.com/botman/driver-telegram

**Pull request merged**
