### PR TITLE
Don't remove inline keyboard automatically (Closes #44, closes #29, closes botman/botman#709)

### LINKED ISSUE #29: Botman with Telegram driver removes Keyboard from chat
When I try to send message like this:
```
bot->reply('blabla', [
            'reply_markup' => json_encode(Collection::make([
            'inline_keyboard' => [ ... ]
        ]))
]);
```
After click on a button , all keyboard will be removed instantly.

I found these lines in listen() method:

```
               if (method_exists($this->getDriver(), 'messagesHandled')) {
                    $this->getDriver()->messagesHandled();
                }
```
Which calls removeInlineKeyboard().
Is it possible to add some kind of manual switcher for this feature? Or better just automatically control if it was a Question, than removeInlineKeyboard, otherwise - don't?

Versions:
"botman/botman": "2.1.10",
"botman/driver-telegram": "1.4",

### LINKED ISSUE #44: Add an option to disable auto hiding keyboard
Now Telegram driver automatically hides keyboard for interactive messages:
https://github.com/botman/driver-telegram/blob/cba2774c81f5aafa6c7590696c817ea285848d16/src/TelegramDriver.php#L164-L173

This method is called here:
https://github.com/botman/botman/blob/0afbda1ad742dd369b0b1368104b6d3462118262/src/BotMan.php#L408-L409

For my case it is required to prevent hiding keyboard, but I did not find a way to do this without extending TelegramDriver and overriding `messagesHandled`. My suggestion is to add an option to TelegramDriver config, for example `'hideKeyboard' => true` (default) and hide a keyboard only if this parameter is set to true. Can make a PR.

### PR DESCRIPTION
**Pull request by kubk**
Implemented without BC break.
#44 
#29 
botman/botman#709

### CODE REVIEW

**Comment by sgomez** [comment]
I think the right behaviour is to send a [answerCallbackQuery](https://core.telegram.org/bots/api#answercallbackquery) request.

**Comment by antimech** [comment]
@mpociot @sschlein

**Comment by antimech** [comment]
@christophrumpel

**Comment by feralheart** [comment]
Hi,
Thank you for your contribution
Closes #44 
closes #29 
closes botman/botman#709

**Pull request merged**
