### PR TITLE
add parse mode

### PR DESCRIPTION
**Pull request by dmamontov**
Docs: https://core.telegram.org/bots/api#markdown-style

### CODE REVIEW

**Comment by mpociot** [comment]
Hi!
Thank you for the PR.

Isn't it better to configure this in the outgoing message, rather than globally through configuration?

For example, this is already possible and would break with this PR, as the global configuration would override the custom setting:

```
$bot->reply('This is **markdown**', [
    'parse_mode' => 'Markdown'
]);
```

We could add this to the global configuration and apply it in the `array_merge_recursive`, so that people could still override it.

**Comment by dmamontov** [comment]
In fact, it is not always convenient to specify locally. Because why repeat the same thing, if for example it is a bot for polls, and there are more than 100 different actions in it! Very messy code becomes. Therefore, in my project, I decided to do it globally!

**Comment by mpociot** [comment]
Yeah you're right. In this case, it will definitely make sense to do this globally.

Can you adjust your code, so that the local configuration could still override the global configuration?

**Comment by christophrumpel** [comment]
@dmamontov did you stop working on that? Would also need that :-)

**Comment by dmamontov** [comment]
Today I'll add an update! He has already done to himself for a long time. missed on github)

**Comment by antimech** [comment]
How Can I do it when I am using `$botman->say($message, $telegram_user_id, TelegramDriver::class);` ?

**Comment by anthonyaxenov** [comment]
@dmamontov @luizjr From one hand I am surprised about `parse_mode` is still not implemented in master (omg). From another hand, I have two things to say since this PR a lil bit diverge with reality.

1) Value of `parse_mode` must be in lowercase. Yes, this is not mentioned in official docs, but in fact when you pass value in another case the message won't be sent.

2) Today we can pass one of **three** values: [`html`](https://core.telegram.org/bots/api#html-style), [`markdown`](https://core.telegram.org/bots/api#markdown-style) (legacy) and [`markdownv2`](https://core.telegram.org/bots/api#markdownv2-style) (richer). Third value is not implemented, first and second ones are implemented wrong.

Since there are no updates maybe later I can propose relevant improvements of 2e7a2ac (if I will not forget).

**Pull request closed without merging**
